[project]
name = "session-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.0.1",
    "jupyterlab>=4.4.9",
    "pandas>=2.3.3",
]
